version: "3.7"

services:
  app1:
    image: app1:latest
    container_name: app1
    networks:
      default:
        ipv4_address: 192.168.1.10
    volumes:
      - app1_data:/data
      - /mnt/nas_share:/app/data

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

volumes:
  app1_data:
    driver: local
  nas_share:
    driver: cifs
    driver_opts:
      username: <username>
      password: <password>
      file_mode: 0777
      dir_mode: 0777
      vers: 3.0
      uid: <uid>
      gid: <gid>
      domain: <domain>
    name: "//<server>/<share>"
